### ISSUE TITLE
Ter certeza de que novas comidas sejam criadas sob FoodController

### ISSUE THREAD

**Issue by void-main-void** [dev-u/emburradinho#72]
Quando cria-se um novo objeto e ele não está na hierarquia de FoodController e adiciona-se a ele o script Food, a Unity dá erro infinitamente.

 - [ ] Verificar se o objeto que tem o script "Food" está sob a hierarquia de FoodController

**Comment by HugoUchoasBorges** [comment]
https://github.com/dev-u/emburradinho/pull/79
