### ISSUE TITLE
Criar plataforma que não da pra atravessar na subida.

### ISSUE THREAD

**Issue by void-main-void** [dev-u/emburradinho#73]
- [x] Criar uma plataforma que não da pra atravessar durante a subida.
 - Quando o jogador colidir com o fundo da plataforma ele deve ter o momento horizontal reduzido.

- [x] Criar um sisteminha de controle de plataformas semelhante ao sistema de controle de comidinhas

**Comment by HugoUchoasBorges** [comment]
https://github.com/dev-u/emburradinho/pull/89
